<?php

/**
 * BaseCadena
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property text $nombre
 * @property Doctrine_Collection $Farmacias
 * 
 * @method text                getNombre()    Returns the current record's "nombre" value
 * @method Doctrine_Collection getFarmacias() Returns the current record's "Farmacias" collection
 * @method Cadena              setNombre()    Sets the current record's "nombre" value
 * @method Cadena              setFarmacias() Sets the current record's "Farmacias" collection
 * 
 * @package    farmacia24h
 * @subpackage model
 * @author     Rodrigo Campos H. rodrigo [at] webdevel [dot] cl
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCadena extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cadena');
        $this->hasColumn('nombre', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Farmacia as Farmacias', array(
             'local' => 'id',
             'foreign' => 'cadena_id'));
    }
}