<?php

/**
 * BaseComuna
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property text $nombre
 * @property integer $region_id
 * @property Region $Region
 * @property Doctrine_Collection $Farmacias
 * @property Doctrine_Collection $Turnos
 * 
 * @method text                getNombre()    Returns the current record's "nombre" value
 * @method integer             getRegionId()  Returns the current record's "region_id" value
 * @method Region              getRegion()    Returns the current record's "Region" value
 * @method Doctrine_Collection getFarmacias() Returns the current record's "Farmacias" collection
 * @method Doctrine_Collection getTurnos()    Returns the current record's "Turnos" collection
 * @method Comuna              setNombre()    Sets the current record's "nombre" value
 * @method Comuna              setRegionId()  Sets the current record's "region_id" value
 * @method Comuna              setRegion()    Sets the current record's "Region" value
 * @method Comuna              setFarmacias() Sets the current record's "Farmacias" collection
 * @method Comuna              setTurnos()    Sets the current record's "Turnos" collection
 * 
 * @package    farmacia24h
 * @subpackage model
 * @author     Rodrigo Campos H. rodrigo [at] webdevel [dot] cl
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComuna extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comuna');
        $this->hasColumn('nombre', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('region_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Region', array(
             'local' => 'region_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Farmacia as Farmacias', array(
             'local' => 'id',
             'foreign' => 'comuna_id'));

        $this->hasMany('Turno as Turnos', array(
             'local' => 'id',
             'foreign' => 'comuna_id'));
    }
}