<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/04/14 17:55:20

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=farmacia24h',
  'username' => 'farmacia24h',
  'password' => 'farmacia24h',
  'name' => 'doctrine',
)),);
