<?php
// auto-generated by sfViewConfigHandler
// date: 2013/04/14 17:55:20
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addMeta('title', 'Farmacia 24h', false, false);
  $response->addMeta('description', 'Farmacia de turno más cercana', false, false);
  $response->addMeta('viewport', 'width=device-width, initial-scale=1.0', false, false);

  $response->addStylesheet('bootstrap.min.css', '', array ());
  $response->addStylesheet('bootstrap-responsive.min.css', '', array ());
  $response->addStylesheet('style.css', '', array ());
  $response->addJavascript('http://code.jquery.com/jquery.js', '', array ());
  $response->addJavascript('bootstrap.min.js', '', array ());
  $response->addJavascript('http://maps.googleapis.com/maps/api/js?key=AIzaSyA-aJwzzVJaqGufJmoG3ZHytkRdAJL9i7k&sensor=true', '', array ());
  $response->addJavascript('farmacia24h.js', '', array ());


