<?php

/**
 * CadenaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CadenaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CadenaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cadena');
    }
}