<?php

/**
 * ComunaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ComunaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ComunaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Comuna');
    }
}