<?php

/**
 * Comuna
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    farmacia24h
 * @subpackage model
 * @author     Rodrigo Campos H. rodrigo [at] webdevel [dot] cl
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Comuna extends BaseComuna
{
}
